# Generated by Django 4.2.4 on 2023-10-04 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
        ('shopapp', '0011_alter_creator_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myauth.profile'),
        ),
    ]
