# Generated by Django 4.2.4 on 2023-10-04 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
        ('shopapp', '0012_alter_creator_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='myauth.profile'),
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
    ]
